/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Apr 05 20:52:40 GMT 2022
 */

package com.xenoamess.x8l.dealers;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class LanguageDealer_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.xenoamess.x8l.dealers.LanguageDealer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "GBK"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\xenoa\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "F:\\workspace\\x8l"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\xenoa"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "xenoa"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(LanguageDealer_ESTest_scaffolding.class.getClassLoader() ,
      "com.fasterxml.jackson.core.JsonParser$NumberType",
      "com.fasterxml.jackson.databind.JsonSerializable$Base",
      "org.dom4j.Node",
      "com.fasterxml.jackson.core.Versioned",
      "org.dom4j.InvalidXPathException",
      "com.fasterxml.jackson.databind.node.TreeTraversingParser",
      "org.apache.commons.lang3.StringUtils",
      "com.xenoamess.x8l.CommentNode",
      "com.fasterxml.jackson.databind.jsontype.TypeSerializer",
      "com.xenoamess.x8l.dealers.LanguageDealer",
      "com.xenoamess.x8l.dealers.JsonDealer",
      "com.fasterxml.jackson.databind.node.NullNode",
      "com.fasterxml.jackson.databind.node.BaseJsonNode",
      "com.xenoamess.x8l.AbstractTreeNode$1",
      "com.fasterxml.jackson.databind.JsonSerializable",
      "com.fasterxml.jackson.databind.JsonNode",
      "org.dom4j.ProcessingInstruction",
      "com.xenoamess.x8l.dealers.X8lDealer$3",
      "com.xenoamess.x8l.dealers.X8lDealer$4",
      "com.xenoamess.x8l.dealers.X8lDealer$1",
      "com.xenoamess.x8l.dealers.X8lDealer$2",
      "com.fasterxml.jackson.databind.node.TextNode",
      "com.fasterxml.jackson.databind.node.ValueNode",
      "com.fasterxml.jackson.databind.node.ArrayNode",
      "com.xenoamess.x8l.dealers.XmlDealer",
      "com.xenoamess.x8l.dealers.JsonDealer$3",
      "com.xenoamess.x8l.dealers.JsonDealer$2",
      "com.xenoamess.x8l.dealers.JsonDealer$1",
      "com.fasterxml.jackson.databind.node.JsonNodeCreator",
      "com.fasterxml.jackson.databind.node.BinaryNode",
      "org.apache.commons.lang3.NotImplementedException",
      "org.dom4j.Document",
      "com.xenoamess.x8l.dealers.X8lDealer",
      "com.xenoamess.x8l.dealers.X8lStatusEnum",
      "com.xenoamess.x8l.X8lTree",
      "com.xenoamess.x8l.databind.x8lpath.X8lPathUtil",
      "com.fasterxml.jackson.core.JsonGenerator",
      "com.xenoamess.x8l.ContentNode",
      "com.xenoamess.x8l.AbstractTreeNode",
      "com.fasterxml.jackson.core.ObjectCodec",
      "com.fasterxml.jackson.databind.DatabindContext",
      "com.fasterxml.jackson.databind.node.ObjectNode",
      "org.dom4j.DocumentException",
      "com.fasterxml.jackson.core.JsonPointer",
      "com.xenoamess.x8l.dealers.XmlDealer$1",
      "org.dom4j.Comment",
      "com.fasterxml.jackson.databind.node.ContainerNode",
      "com.xenoamess.x8l.dealers.XmlDealer$4",
      "com.xenoamess.x8l.X8lGrammarException",
      "com.xenoamess.x8l.dealers.XmlDealer$3",
      "com.xenoamess.x8l.dealers.XmlDealer$2",
      "com.fasterxml.jackson.databind.SerializerProvider",
      "org.dom4j.Visitor",
      "com.fasterxml.jackson.core.JsonToken",
      "com.xenoamess.x8l.databind.X8lDataBeanFieldScheme",
      "org.apache.commons.lang3.function.ToBooleanBiFunction",
      "org.dom4j.CharacterData",
      "com.fasterxml.jackson.databind.node.JsonNodeType",
      "com.xenoamess.x8l.TextNode",
      "com.fasterxml.jackson.core.TreeNode",
      "com.fasterxml.jackson.databind.node.NumericNode",
      "com.fasterxml.jackson.core.TreeCodec",
      "org.dom4j.NodeFilter",
      "com.fasterxml.jackson.core.JsonParser",
      "org.dom4j.Branch",
      "com.fasterxml.jackson.databind.ObjectMapper",
      "org.apache.commons.vfs2.FileObject",
      "org.dom4j.XPath",
      "com.fasterxml.jackson.core.base.ParserMinimalBase",
      "com.xenoamess.x8l.RootNode",
      "com.xenoamess.x8l.dealers.AbstractLanguageDealerHandler",
      "com.fasterxml.jackson.databind.node.MissingNode",
      "com.fasterxml.jackson.databind.node.BooleanNode",
      "org.dom4j.Element",
      "org.dom4j.QName",
      "com.fasterxml.jackson.databind.util.RawValue"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(LanguageDealer_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.xenoamess.x8l.dealers.LanguageDealer",
      "com.xenoamess.x8l.AbstractTreeNode",
      "com.xenoamess.x8l.ContentNode",
      "com.xenoamess.x8l.RootNode",
      "com.xenoamess.x8l.dealers.X8lDealer$1",
      "com.xenoamess.x8l.dealers.X8lDealer$2",
      "com.xenoamess.x8l.dealers.X8lDealer$3",
      "com.xenoamess.x8l.dealers.X8lDealer$4",
      "com.xenoamess.x8l.dealers.X8lDealer",
      "com.xenoamess.x8l.dealers.X8lStatusEnum",
      "com.xenoamess.x8l.TextNode",
      "com.xenoamess.x8l.dealers.JsonDealer$1",
      "com.xenoamess.x8l.dealers.JsonDealer$2",
      "com.xenoamess.x8l.dealers.JsonDealer$3",
      "com.xenoamess.x8l.dealers.JsonDealer",
      "com.xenoamess.x8l.dealers.XmlDealer$1",
      "com.xenoamess.x8l.dealers.XmlDealer$2",
      "com.xenoamess.x8l.dealers.XmlDealer$3",
      "com.xenoamess.x8l.dealers.XmlDealer$4",
      "com.xenoamess.x8l.dealers.XmlDealer",
      "com.xenoamess.x8l.X8lTree",
      "com.xenoamess.x8l.AbstractTreeNode$1",
      "com.xenoamess.x8l.databind.x8lpath.X8lPathUtil",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.lang3.NotImplementedException",
      "com.xenoamess.x8l.CommentNode",
      "com.xenoamess.x8l.X8lGrammarException"
    );
  }
}
