/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 05 20:54:55 GMT 2022
 */

package com.xenoamess.x8l;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class PackageVersion_ESTest extends PackageVersion_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        PackageVersion packageVersion0 = new PackageVersion();
    }
}
