/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 05 20:54:40 GMT 2022
 */

package com.xenoamess.x8l;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class TextNode_ESTest extends TextNode_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        RootNode rootNode0 = new RootNode((ContentNode) null);
        TextNode textNode0 = new TextNode(rootNode0, 0, "");
        textNode0.clear();
        String string0 = textNode0.getTextContent();
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test01() throws Throwable {
        TextNode textNode0 = new TextNode((ContentNode) null, 3073, "readResolve");
        String string0 = textNode0.getTextContent();
        assertEquals("readResolve", string0);
    }

    @Test(timeout = 4000)
    public void test02() throws Throwable {
        RootNode rootNode0 = new RootNode((ContentNode) null, 0);
        TextNode textNode0 = new TextNode(rootNode0, 0, " ");
        rootNode0.changeParentAndRegister((ContentNode) rootNode0, 0);
        // Undeclared exception!
        try {
            textNode0.show();
            fail("Expecting exception: StackOverflowError");

        } catch (StackOverflowError e) {
            //
            // no message in exception (getMessage() returned null)
            //
        }
    }

    @Test(timeout = 4000)
    public void test03() throws Throwable {
        RootNode rootNode0 = new RootNode((ContentNode) null, 0);
        TextNode textNode0 = new TextNode(rootNode0, 0, "");
        textNode0.clear();
        // Undeclared exception!
        try {
            textNode0.show();
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // Argument for @NotNull parameter 'originalString' of com/xenoamess/x8l/X8lTree.transcodeText must not be null
            //
            verifyException("com.xenoamess.x8l.X8lTree", e);
        }
    }

    @Test(timeout = 4000)
    public void test04() throws Throwable {
        ContentNode contentNode0 = new ContentNode((ContentNode) null, 2087);
        RootNode rootNode0 = new RootNode(contentNode0, 0);
        TextNode textNode0 = new TextNode(rootNode0, " ");
        textNode0.clear();
        // Undeclared exception!
        try {
            textNode0.format(1);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("com.xenoamess.x8l.TextNode", e);
        }
    }

    @Test(timeout = 4000)
    public void test05() throws Throwable {
        RootNode rootNode0 = new RootNode((ContentNode) null);
        TextNode textNode0 = null;
        try {
            textNode0 = new TextNode(rootNode0, 23, " ");
            fail("Expecting exception: IndexOutOfBoundsException");

        } catch (IndexOutOfBoundsException e) {
            //
            // Index: 23, Size: 0
            //
            verifyException("java.util.ArrayList", e);
        }
    }

    @Test(timeout = 4000)
    public void test06() throws Throwable {
        RootNode rootNode0 = new RootNode((ContentNode) null);
        TextNode textNode0 = new TextNode(rootNode0, (String) null);
        assertEquals("", textNode0.getTextContent());
    }

    @Test(timeout = 4000)
    public void test07() throws Throwable {
        ContentNode contentNode0 = new ContentNode((ContentNode) null);
        TextNode textNode0 = new TextNode(contentNode0, "");
        textNode0.setTextContent("");
        assertEquals("", textNode0.getTextContent());
    }

    @Test(timeout = 4000)
    public void test08() throws Throwable {
        TextNode textNode0 = new TextNode((ContentNode) null, "r7#i5dZLl%C");
        textNode0.equals(textNode0);
        assertEquals("r7#i5dZLl%C", textNode0.getTextContent());
    }

    @Test(timeout = 4000)
    public void test09() throws Throwable {
        TextNode textNode0 = new TextNode((ContentNode) null, (-913), "");
        boolean boolean0 = textNode0.equals((Object) null);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test10() throws Throwable {
        ContentNode contentNode0 = new ContentNode((ContentNode) null, 2087);
        RootNode rootNode0 = new RootNode(contentNode0, 0);
        TextNode textNode0 = new TextNode(rootNode0, " ");
        boolean boolean0 = textNode0.equals(rootNode0);
        assertEquals(" ", textNode0.getTextContent());
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test11() throws Throwable {
        TextNode textNode0 = new TextNode((ContentNode) null, 1339, (String) null);
        assertEquals("", textNode0.getTextContent());
    }

    @Test(timeout = 4000)
    public void test12() throws Throwable {
        RootNode rootNode0 = new RootNode((ContentNode) null);
        TextNode textNode0 = new TextNode(rootNode0, 0, "");
        String string0 = textNode0.getTextContent();
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test13() throws Throwable {
        TextNode textNode0 = new TextNode((ContentNode) null, "B");
        textNode0.clear();
        TextNode textNode1 = textNode0.copy();
        assertEquals("", textNode1.getTextContent());
    }

    @Test(timeout = 4000)
    public void test14() throws Throwable {
        ContentNode contentNode0 = new ContentNode((ContentNode) null, 2087);
        RootNode rootNode0 = new RootNode(contentNode0, 0);
        TextNode textNode0 = new TextNode(rootNode0, " ");
        textNode0.format(1);
        assertEquals("", textNode0.getTextContent());
    }

    @Test(timeout = 4000)
    public void test15() throws Throwable {
        TextNode textNode0 = new TextNode((ContentNode) null, "r7#i5dZLl%C");
        textNode0.close();
        // Undeclared exception!
        try {
            textNode0.equals(textNode0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
        }
    }

    @Test(timeout = 4000)
    public void test16() throws Throwable {
        TextNode textNode0 = new TextNode((ContentNode) null, "r7#i5dZLl%C");
        textNode0.show();
        assertEquals("r7#i5dZLl%C", textNode0.getTextContent());
    }
}
