/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Tue Apr 05 20:54:40 GMT 2022
 */

package com.xenoamess.x8l;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class TextNode_ESTest_scaffolding {

    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

    private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();

    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "com.xenoamess.x8l.TextNode";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    public static void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("file.encoding", "GBK");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\xenoa\\AppData\\Local\\Temp\\");
        java.lang.System.setProperty("user.country", "CN");
        java.lang.System.setProperty("user.dir", "F:\\workspace\\x8l");
        java.lang.System.setProperty("user.home", "C:\\Users\\xenoa");
        java.lang.System.setProperty("user.language", "zh");
        java.lang.System.setProperty("user.name", "xenoa");
        java.lang.System.setProperty("user.timezone", "");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TextNode_ESTest_scaffolding.class.getClassLoader(),
                "com.fasterxml.jackson.databind.introspect.ClassIntrospector",
                "com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy$Provider",
                "com.fasterxml.jackson.databind.JsonSerializable$Base",
                "com.fasterxml.jackson.databind.MappingIterator",
                "com.fasterxml.jackson.databind.node.NodeCursor",
                "com.fasterxml.jackson.databind.node.TreeTraversingParser",
                "org.apache.commons.lang3.StringUtils",
                "com.fasterxml.jackson.databind.jsontype.TypeSerializer",
                "org.dom4j.Entity",
                "com.xenoamess.x8l.dealers.LanguageDealer",
                "com.xenoamess.x8l.dealers.JsonDealer",
                "com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator",
                "com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator$Base",
                "com.fasterxml.jackson.databind.jsonschema.JsonSchema",
                "com.fasterxml.jackson.databind.type.TypeFactory",
                "com.fasterxml.jackson.databind.cfg.MapperConfigBase",
                "com.fasterxml.jackson.databind.type.ArrayType",
                "com.fasterxml.jackson.databind.ser.impl.UnknownSerializer",
                "com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWithSerializerProvider",
                "com.fasterxml.jackson.core.JacksonException",
                "com.fasterxml.jackson.databind.type.MapLikeType",
                "org.dom4j.ProcessingInstruction",
                "com.fasterxml.jackson.databind.type.MapType",
                "com.xenoamess.x8l.dealers.X8lDealer$3",
                "com.fasterxml.jackson.databind.util.Named",
                "com.xenoamess.x8l.dealers.X8lDealer$4",
                "com.xenoamess.x8l.dealers.X8lDealer$1",
                "com.xenoamess.x8l.dealers.X8lDealer$2",
                "org.dom4j.Namespace",
                "com.fasterxml.jackson.databind.ObjectWriter",
                "org.apache.commons.vfs2.FileSystemException",
                "com.fasterxml.jackson.databind.type.TypeBase",
                "com.fasterxml.jackson.databind.type.CollectionType",
                "com.fasterxml.jackson.core.StreamWriteFeature",
                "com.fasterxml.jackson.core.StreamReadFeature",
                "com.fasterxml.jackson.databind.node.TextNode",
                "com.fasterxml.jackson.databind.node.ValueNode",
                "com.fasterxml.jackson.databind.ser.BasicSerializerFactory",
                "com.fasterxml.jackson.databind.util.ClassUtil$Ctor",
                "com.fasterxml.jackson.databind.node.JsonNodeCreator",
                "com.fasterxml.jackson.core.async.NonBlockingInputFeeder",
                "com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper",
                "com.fasterxml.jackson.core.JsonLocation",
                "com.fasterxml.jackson.databind.exc.MismatchedInputException",
                "com.fasterxml.jackson.databind.type.TypeParser",
                "com.fasterxml.jackson.annotation.JsonSetter$Value",
                "com.fasterxml.jackson.databind.jsontype.SubtypeResolver",
                "com.fasterxml.jackson.core.ObjectCodec",
                "org.dom4j.tree.QNameCache",
                "com.xenoamess.x8l.dealers.XmlDealer$1",
                "com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitable",
                "com.xenoamess.x8l.dealers.XmlDealer$4",
                "com.xenoamess.x8l.dealers.XmlDealer$3",
                "com.xenoamess.x8l.dealers.XmlDealer$2",
                "com.xenoamess.x8l.databind.X8lDataBeanFieldScheme",
                "com.fasterxml.jackson.databind.type.CollectionLikeType",
                "com.xenoamess.x8l.TextNode",
                "com.fasterxml.jackson.core.TreeNode",
                "com.fasterxml.jackson.databind.node.NumericNode",
                "com.fasterxml.jackson.annotation.ObjectIdResolver",
                "org.dom4j.NodeFilter",
                "com.fasterxml.jackson.databind.DeserializationContext",
                "org.apache.commons.vfs2.FileObject",
                "com.fasterxml.jackson.databind.type.ResolvedRecursiveType",
                "com.fasterxml.jackson.databind.introspect.BasicClassIntrospector",
                "com.fasterxml.jackson.core.base.ParserMinimalBase",
                "com.fasterxml.jackson.databind.ser.PropertyWriter",
                "com.fasterxml.jackson.core.util.ByteArrayBuilder",
                "com.fasterxml.jackson.databind.type.ReferenceType",
                "com.xenoamess.x8l.RootNode",
                "org.apache.commons.vfs2.FileType",
                "org.dom4j.QName",
                "com.fasterxml.jackson.databind.ObjectMapper$DefaultTyping",
                "com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition",
                "com.fasterxml.jackson.databind.Module",
                "com.fasterxml.jackson.annotation.JsonView",
                "com.fasterxml.jackson.databind.util.Converter",
                "com.fasterxml.jackson.databind.AnnotationIntrospector",
                "org.dom4j.Node",
                "com.fasterxml.jackson.databind.ser.std.NullSerializer",
                "org.dom4j.util.SingletonStrategy",
                "com.fasterxml.jackson.core.SerializableString",
                "com.fasterxml.jackson.core.Versioned",
                "com.fasterxml.jackson.databind.introspect.VirtualAnnotatedMember",
                "com.fasterxml.jackson.databind.exc.InvalidTypeIdException",
                "com.fasterxml.jackson.databind.DeserializationFeature",
                "com.fasterxml.jackson.annotation.JacksonAnnotation",
                "com.fasterxml.jackson.databind.ObjectReader",
                "com.fasterxml.jackson.databind.node.BaseJsonNode",
                "com.fasterxml.jackson.core.util.RequestPayload",
                "com.fasterxml.jackson.databind.JsonSerializable",
                "com.fasterxml.jackson.databind.introspect.AnnotatedMember",
                "com.fasterxml.jackson.databind.util.LRUMap",
                "com.fasterxml.jackson.databind.BeanDescription",
                "com.fasterxml.jackson.databind.JsonDeserializer",
                "com.fasterxml.jackson.databind.introspect.AccessorNamingStrategy",
                "com.fasterxml.jackson.databind.util.SimpleBeanPropertyDefinition",
                "com.fasterxml.jackson.annotation.JsonRawValue",
                "com.fasterxml.jackson.databind.introspect.AnnotatedWithParams",
                "com.fasterxml.jackson.databind.node.ArrayNode",
                "com.fasterxml.jackson.core.Base64Variant",
                "com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility",
                "org.apache.commons.vfs2.FileName",
                "com.fasterxml.jackson.databind.ser.impl.AttributePropertyWriter",
                "com.fasterxml.jackson.databind.util.LookupCache",
                "com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy",
                "com.fasterxml.jackson.databind.exc.InvalidFormatException",
                "com.fasterxml.jackson.databind.ser.SerializerFactory",
                "com.xenoamess.x8l.databind.x8lpath.X8lPathUtil",
                "com.fasterxml.jackson.core.io.CharacterEscapes",
                "com.xenoamess.x8l.AbstractTreeNode",
                "com.fasterxml.jackson.databind.type.SimpleType",
                "com.fasterxml.jackson.databind.ser.ContextualSerializer",
                "com.fasterxml.jackson.core.type.ResolvedType",
                "com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$RecordNaming",
                "com.fasterxml.jackson.databind.MapperFeature",
                "com.fasterxml.jackson.databind.DeserializationConfig",
                "com.fasterxml.jackson.databind.Module$SetupContext",
                "com.fasterxml.jackson.databind.annotation.JsonSerialize",
                "com.fasterxml.jackson.databind.ext.Java7SupportImpl",
                "com.fasterxml.jackson.databind.util.ClassUtil",
                "com.fasterxml.jackson.databind.node.ContainerNode",
                "com.fasterxml.jackson.databind.introspect.AnnotatedMethod",
                "org.apache.commons.lang3.function.ToBooleanBiFunction",
                "com.fasterxml.jackson.databind.deser.BeanDeserializerFactory",
                "com.fasterxml.jackson.databind.ser.std.StdSerializer",
                "com.fasterxml.jackson.databind.jsontype.TypeIdResolver",
                "com.fasterxml.jackson.databind.ser.BeanSerializerFactory",
                "com.fasterxml.jackson.databind.type.LogicalType",
                "com.fasterxml.jackson.databind.PropertyNamingStrategy",
                "com.fasterxml.jackson.databind.introspect.VisibilityChecker",
                "com.fasterxml.jackson.core.JsonParser",
                "org.dom4j.Branch",
                "com.fasterxml.jackson.databind.jsonschema.SchemaAware",
                "com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
                "com.fasterxml.jackson.core.JsonProcessingException",
                "com.fasterxml.jackson.core.JsonStreamContext",
                "com.fasterxml.jackson.core.Base64Variants",
                "org.dom4j.XPath",
                "com.fasterxml.jackson.databind.ser.VirtualBeanPropertyWriter",
                "com.xenoamess.x8l.dealers.AbstractLanguageDealerHandler",
                "org.dom4j.Element",
                "com.fasterxml.jackson.databind.cfg.MutableConfigOverride",
                "com.fasterxml.jackson.core.PrettyPrinter",
                "com.fasterxml.jackson.core.util.JacksonFeatureSet",
                "com.fasterxml.jackson.databind.util.RawValue",
                "com.fasterxml.jackson.core.TokenStreamFactory",
                "org.apache.commons.vfs2.FileContent",
                "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl",
                "com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector",
                "org.apache.commons.vfs2.FileSelector",
                "org.dom4j.InvalidXPathException",
                "com.fasterxml.jackson.databind.jsontype.impl.StdSubtypeResolver",
                "com.fasterxml.jackson.core.util.JacksonFeature",
                "com.fasterxml.jackson.core.exc.InputCoercionException",
                "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
                "com.fasterxml.jackson.annotation.JsonInclude$Include",
                "com.fasterxml.jackson.databind.node.NullNode",
                "com.fasterxml.jackson.databind.JsonSerializer",
                "com.fasterxml.jackson.databind.jsontype.NamedType",
                "com.fasterxml.jackson.databind.JsonNode",
                "com.fasterxml.jackson.databind.introspect.DefaultAccessorNamingStrategy$Provider",
                "com.fasterxml.jackson.databind.jsontype.TypeResolverBuilder",
                "com.fasterxml.jackson.databind.ser.ResolvableSerializer",
                "com.fasterxml.jackson.databind.introspect.ObjectIdInfo",
                "com.fasterxml.jackson.databind.introspect.NopAnnotationIntrospector",
                "com.fasterxml.jackson.core.StreamReadCapability",
                "com.fasterxml.jackson.databind.BeanProperty",
                "com.fasterxml.jackson.core.Version",
                "com.fasterxml.jackson.databind.DatabindException",
                "com.fasterxml.jackson.databind.deser.BasicDeserializerFactory",
                "com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer",
                "com.fasterxml.jackson.databind.node.JsonNodeFactory",
                "com.fasterxml.jackson.databind.introspect.TypeResolutionContext",
                "com.fasterxml.jackson.databind.cfg.MapperConfig",
                "com.fasterxml.jackson.annotation.JsonManagedReference",
                "com.fasterxml.jackson.databind.annotation.JsonDeserialize",
                "org.dom4j.Attribute",
                "com.fasterxml.jackson.databind.node.BinaryNode",
                "com.fasterxml.jackson.core.Base64Variant$PaddingReadBehaviour",
                "org.dom4j.Document",
                "com.fasterxml.jackson.core.io.JsonEOFException",
                "com.xenoamess.x8l.dealers.X8lDealer",
                "com.fasterxml.jackson.core.exc.StreamWriteException",
                "com.fasterxml.jackson.databind.MappingJsonFactory",
                "com.fasterxml.jackson.databind.InjectableValues",
                "com.xenoamess.x8l.X8lTree",
                "com.fasterxml.jackson.core.JsonGenerator",
                "com.xenoamess.x8l.ContentNode",
                "com.fasterxml.jackson.databind.deser.DefaultDeserializationContext",
                "com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair",
                "com.fasterxml.jackson.databind.cfg.CoercionConfig",
                "com.fasterxml.jackson.databind.node.NodeCursor$RootCursor",
                "com.fasterxml.jackson.core.JsonEncoding",
                "org.dom4j.CDATA",
                "com.fasterxml.jackson.core.JsonGenerationException",
                "org.dom4j.tree.AbstractNode",
                "org.dom4j.Visitor",
                "com.fasterxml.jackson.databind.JavaType",
                "org.dom4j.CharacterData",
                "com.fasterxml.jackson.databind.node.JsonNodeType",
                "com.fasterxml.jackson.core.TreeCodec",
                "com.fasterxml.jackson.annotation.JsonAutoDetect$Value",
                "com.fasterxml.jackson.databind.deser.NullValueProvider",
                "com.fasterxml.jackson.annotation.JacksonAnnotationValue",
                "com.fasterxml.jackson.databind.introspect.Annotated",
                "com.fasterxml.jackson.core.type.WritableTypeId",
                "com.fasterxml.jackson.core.StreamWriteCapability",
                "com.fasterxml.jackson.core.JsonFactory",
                "com.fasterxml.jackson.databind.node.MissingNode",
                "com.fasterxml.jackson.databind.node.BooleanNode",
                "com.fasterxml.jackson.databind.util.StdDateFormat",
                "com.fasterxml.jackson.databind.util.TokenBuffer",
                "org.apache.commons.vfs2.FileSystem",
                "com.fasterxml.jackson.core.JsonParser$NumberType",
                "com.fasterxml.jackson.databind.type.PlaceholderForType",
                "org.apache.commons.vfs2.NameScope",
                "com.fasterxml.jackson.databind.SerializationConfig",
                "com.xenoamess.x8l.CommentNode",
                "com.fasterxml.jackson.annotation.JsonFormat$Value",
                "com.fasterxml.jackson.annotation.JsonInclude$Value",
                "org.dom4j.DocumentType",
                "com.xenoamess.x8l.AbstractTreeNode$1",
                "com.fasterxml.jackson.databind.jsontype.impl.LaissezFaireSubTypeValidator",
                "com.fasterxml.jackson.core.type.TypeReference",
                "com.fasterxml.jackson.core.JsonParseException",
                "com.fasterxml.jackson.databind.annotation.JacksonStdImpl",
                "com.fasterxml.jackson.databind.introspect.ConcreteBeanPropertyBase",
                "com.fasterxml.jackson.databind.cfg.ConstructorDetector",
                "com.fasterxml.jackson.annotation.JsonBackReference",
                "com.fasterxml.jackson.databind.ser.FilterProvider",
                "com.fasterxml.jackson.annotation.JsonFormat",
                "com.fasterxml.jackson.databind.deser.DeserializerFactory",
                "com.xenoamess.x8l.dealers.XmlDealer",
                "com.fasterxml.jackson.databind.introspect.AnnotatedClass",
                "com.fasterxml.jackson.annotation.JsonTypeInfo",
                "com.fasterxml.jackson.databind.ser.std.ToEmptyObjectSerializer",
                "org.dom4j.util.SimpleSingleton",
                "com.fasterxml.jackson.databind.ser.impl.FailingSerializer",
                "com.fasterxml.jackson.annotation.JsonUnwrapped",
                "com.xenoamess.x8l.dealers.JsonDealer$3",
                "com.xenoamess.x8l.dealers.JsonDealer$2",
                "com.xenoamess.x8l.dealers.JsonDealer$1",
                "com.fasterxml.jackson.databind.JsonMappingException",
                "com.fasterxml.jackson.databind.introspect.ClassIntrospector$MixInResolver",
                "org.apache.commons.lang3.NotImplementedException",
                "com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer",
                "com.xenoamess.x8l.dealers.X8lStatusEnum",
                "com.fasterxml.jackson.annotation.JsonTypeInfo$As",
                "com.fasterxml.jackson.databind.DatabindContext",
                "com.fasterxml.jackson.databind.node.ObjectNode",
                "com.fasterxml.jackson.core.JsonFactory$Feature",
                "com.fasterxml.jackson.databind.cfg.ConfigOverride",
                "org.dom4j.DocumentFactory",
                "org.dom4j.DocumentException",
                "com.fasterxml.jackson.core.JsonPointer",
                "com.fasterxml.jackson.core.JsonParser$Feature",
                "com.fasterxml.jackson.annotation.JsonMerge",
                "com.fasterxml.jackson.core.io.SegmentedStringWriter",
                "com.fasterxml.jackson.databind.deser.DeserializationProblemHandler",
                "org.apache.commons.vfs2.operations.FileOperations",
                "com.fasterxml.jackson.databind.type.TypeBindings",
                "com.fasterxml.jackson.databind.ser.impl.WritableObjectId",
                "org.dom4j.Comment",
                "com.xenoamess.x8l.X8lGrammarException",
                "com.fasterxml.jackson.annotation.PropertyAccessor",
                "com.fasterxml.jackson.databind.SerializerProvider",
                "com.fasterxml.jackson.core.JsonToken",
                "com.fasterxml.jackson.databind.cfg.ContextAttributes",
                "com.fasterxml.jackson.databind.cfg.MutableCoercionConfig",
                "com.fasterxml.jackson.core.JsonGenerator$Feature",
                "com.fasterxml.jackson.databind.cfg.BaseSettings",
                "com.fasterxml.jackson.databind.ObjectMapper",
                "com.fasterxml.jackson.core.exc.StreamReadException",
                "org.dom4j.Text",
                "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl",
                "com.fasterxml.jackson.annotation.ObjectIdGenerator",
                "com.fasterxml.jackson.databind.cfg.HandlerInstantiator",
                "com.fasterxml.jackson.databind.ext.Java7Support",
                "com.fasterxml.jackson.databind.cfg.ConfigFeature",
                "com.fasterxml.jackson.databind.exc.InvalidDefinitionException",
                "com.fasterxml.jackson.core.FormatSchema",
                "com.fasterxml.jackson.databind.SerializationFeature"
        );
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TextNode_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
                "com.xenoamess.x8l.AbstractTreeNode",
                "com.xenoamess.x8l.TextNode",
                "com.xenoamess.x8l.ContentNode",
                "com.xenoamess.x8l.RootNode",
                "com.xenoamess.x8l.dealers.LanguageDealer",
                "com.xenoamess.x8l.dealers.X8lDealer$1",
                "com.xenoamess.x8l.dealers.X8lDealer$2",
                "com.xenoamess.x8l.dealers.X8lDealer$3",
                "com.xenoamess.x8l.dealers.X8lDealer$4",
                "com.xenoamess.x8l.dealers.X8lDealer",
                "com.xenoamess.x8l.dealers.JsonDealer$1",
                "com.xenoamess.x8l.dealers.JsonDealer$2",
                "com.xenoamess.x8l.dealers.JsonDealer$3",
                "com.xenoamess.x8l.dealers.JsonDealer",
                "com.xenoamess.x8l.dealers.XmlDealer$1",
                "com.xenoamess.x8l.dealers.XmlDealer$2",
                "com.xenoamess.x8l.dealers.XmlDealer$3",
                "com.xenoamess.x8l.dealers.XmlDealer$4",
                "com.xenoamess.x8l.dealers.XmlDealer",
                "com.xenoamess.x8l.X8lTree",
                "com.xenoamess.x8l.AbstractTreeNode$1",
                "com.xenoamess.x8l.databind.x8lpath.X8lPathUtil",
                "org.apache.commons.lang3.NotImplementedException",
                "org.apache.commons.lang3.StringUtils",
                "com.xenoamess.x8l.dealers.X8lStatusEnum",
                "com.xenoamess.x8l.X8lGrammarException",
                "com.xenoamess.x8l.CommentNode"
        );
    }
}
