/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 05 20:55:01 GMT 2022
 */

package com.xenoamess.x8l;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertFalse;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class X8lGrammarException_ESTest extends X8lGrammarException_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        X8lGrammarException x8lGrammarException0 = new X8lGrammarException("com.xenoamess.x8l.X8lGrammarException");
        X8lGrammarException x8lGrammarException1 = new X8lGrammarException("", x8lGrammarException0);
        assertFalse(x8lGrammarException1.equals((Object) x8lGrammarException0));
    }
}
