/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 05 20:52:40 GMT 2022
 */

package com.xenoamess.x8l.dealers;

import java.io.Reader;
import java.io.StringReader;
import java.io.StringWriter;
import java.io.Writer;

import com.xenoamess.x8l.ContentNode;
import com.xenoamess.x8l.RootNode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class LanguageDealer_ESTest extends LanguageDealer_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        LanguageDealer languageDealer0 = new LanguageDealer();
        StringWriter stringWriter0 = new StringWriter();
        RootNode rootNode0 = new RootNode((ContentNode) null);
        boolean boolean0 = languageDealer0.write((Writer) stringWriter0, (ContentNode) rootNode0);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        StringReader stringReader0 = new StringReader("}TE");
        RootNode rootNode0 = new RootNode((ContentNode) null, 0);
        rootNode0.read((Reader) stringReader0);
        assertEquals("", rootNode0.getName());
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        LanguageDealer languageDealer0 = new LanguageDealer();
        StringWriter stringWriter0 = new StringWriter();
        // Undeclared exception!
        try {
            languageDealer0.write((Writer) stringWriter0, (ContentNode) null);
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // Argument for @NotNull parameter 'abstractTreeNode' of com/xenoamess/x8l/dealers/LanguageDealer.write must not be null
            //
            verifyException("com.xenoamess.x8l.dealers.LanguageDealer", e);
        }
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        LanguageDealer languageDealer0 = new LanguageDealer();
        // Undeclared exception!
        try {
            languageDealer0.write((Writer) null, (RootNode) null);
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // Argument for @NotNull parameter 'writer' of com/xenoamess/x8l/dealers/LanguageDealer.write must not be null
            //
            verifyException("com.xenoamess.x8l.dealers.LanguageDealer", e);
        }
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        RootNode rootNode0 = new RootNode((ContentNode) null);
        rootNode0.show();
        assertEquals("", rootNode0.getName());
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        LanguageDealer languageDealer0 = new LanguageDealer();
        StringReader stringReader0 = new StringReader("4uyk");
        ContentNode contentNode0 = new ContentNode((ContentNode) null, 3);
        RootNode rootNode0 = new RootNode(contentNode0);
        boolean boolean0 = languageDealer0.read((Reader) stringReader0, rootNode0);
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test6() throws Throwable {
        LanguageDealer languageDealer0 = new LanguageDealer();
        // Undeclared exception!
        try {
            languageDealer0.read((Reader) null, (ContentNode) null);
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // Argument for @NotNull parameter 'reader' of com/xenoamess/x8l/dealers/LanguageDealer.read must not be null
            //
            verifyException("com.xenoamess.x8l.dealers.LanguageDealer", e);
        }
    }

    @Test(timeout = 4000)
    public void test7() throws Throwable {
        LanguageDealer languageDealer0 = new LanguageDealer();
        StringReader stringReader0 = new StringReader("cR\"N[{ce!1vJB$dsCBg");
        // Undeclared exception!
        try {
            languageDealer0.read((Reader) stringReader0, (RootNode) null);
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // Argument for @NotNull parameter 'abstractTreeNode' of com/xenoamess/x8l/dealers/LanguageDealer.read must not be null
            //
            verifyException("com.xenoamess.x8l.dealers.LanguageDealer", e);
        }
    }

    @Test(timeout = 4000)
    public void test8() throws Throwable {
        LanguageDealer languageDealer0 = new LanguageDealer();
        // Undeclared exception!
        try {
            languageDealer0.registerTreeNodeHandler((Class<RootNode>) null, (AbstractLanguageDealerHandler<RootNode>) null);
            fail("Expecting exception: IllegalArgumentException");

        } catch (IllegalArgumentException e) {
            //
            // Argument for @NotNull parameter 'tClass' of com/xenoamess/x8l/dealers/LanguageDealer.registerTreeNodeHandler must not be null
            //
            verifyException("com.xenoamess.x8l.dealers.LanguageDealer", e);
        }
    }
}
