/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 05 20:54:44 GMT 2022
 */

package com.xenoamess.x8l.databind;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.xenoamess.x8l.X8lTree;
import com.xenoamess.x8l.databind.TestDataBean1;
import com.xenoamess.x8l.databind.TestDataBean2;
import com.xenoamess.x8l.databind.X8lDataBean;
import com.xenoamess.x8l.dealers.LanguageDealer;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class X8lDataBean_ESTest extends X8lDataBean_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      X8lTree x8lTree0 = new X8lTree();
      Class<TestDataBean1> class0 = TestDataBean1.class;
      TestDataBean1 testDataBean1_0 = X8lDataBean.buildFromX8lTree(class0, x8lTree0);
      assertNotNull(testDataBean1_0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestDataBean2 testDataBean2_0 = new TestDataBean2();
      // Undeclared exception!
      try { 
        testDataBean2_0.loadFromX8lTree((X8lTree) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Argument for @NotNull parameter 'x8lTree' of com/xenoamess/x8l/databind/X8lDataBean.loadFromX8lTree must not be null
         //
         verifyException("com.xenoamess.x8l.databind.X8lDataBean", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TestDataBean2 testDataBean2_0 = new TestDataBean2();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0, 2141);
      DataInputStream dataInputStream0 = new DataInputStream(pipedInputStream0);
      LanguageDealer languageDealer0 = new LanguageDealer();
      X8lTree x8lTree0 = X8lTree.load((InputStream) dataInputStream0, languageDealer0);
      testDataBean2_0.loadFromX8lTree(x8lTree0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        X8lDataBean.buildFromX8lTree((Class<X8lDataBean>) null, (X8lTree) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Argument for @NotNull parameter 'tClass' of com/xenoamess/x8l/databind/X8lDataBean.buildFromX8lTree must not be null
         //
         verifyException("com.xenoamess.x8l.databind.X8lDataBean", e);
      }
  }
}
